spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/EmployeeManagmentSystem
      database: EmployeeManagmentSystem
      auto-index-creation: true
  application:
    name: EmployeeManagementSystem


  mail:
    host: smtp.gmail.com
    port: 587
    username : sankeths908@gmail.com
    password: sqeg pffu bxys opyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true